### ISSUE TITLE
go1.21rc3 compatibility

### ISSUE THREAD

**Issue by RealHarshThakur** [bradfitz/go-tool-cache#3]
Hey Brad, really excited for this one. Coming off of this [issue](https://github.com/golang/go/issues/59719), I'm on go1.21rc3 and I tried out what the readme suggested but didn't see any output stats. I'm probably missing something/doing something silly.  

<img width="872" alt="Screenshot 2023-07-19 at 3 44 55 AM" src="https://github.com/bradfitz/go-tool-cache/assets/38140305/95977d90-c94e-4fe8-a6a3-f75d5a11103b">

**Comment by danp** [comment]
@RealHarshThakur `GOEXPERIMENT` needs to be set at toolchain build time, not your program build time. So, for example, you need to follow directions at https://go.dev/doc/install/source and have `GOEXPERIMENT=cacheprog` set when you run `make.bash`, `all.bash` or equivalent.

**Comment by RealHarshThakur** [comment]
thanks for clarifying @danp :)
